#!/bin/bash
# Setup auditd rules to monitor the openclaw user
# Run as root

set -euo pipefail

WATCHED_USER="openclaw"
WATCHED_UID=$(id -u "$WATCHED_USER" 2>/dev/null || echo "")

if [ -z "$WATCHED_UID" ]; then
    echo "ERROR: User '$WATCHED_USER' not found"
    exit 1
fi

# Detect architecture for correct syscall names
ARCH=$(uname -m)
echo "Detected architecture: $ARCH"

case "$ARCH" in
    x86_64)
        PERM_SYSCALLS="chmod,fchmod,chown,fchown"
        ;;
    aarch64)
        # ARM64 doesn't have chmod/chown syscalls; uses fchmodat/fchownat instead
        PERM_SYSCALLS="fchmodat,fchmod,fchownat,fchown"
        ;;
    *)
        echo "WARNING: Unknown architecture '$ARCH', falling back to fchmodat/fchownat (portable)"
        PERM_SYSCALLS="fchmodat,fchmod,fchownat,fchown"
        ;;
esac

echo "Setting up auditd rules for user $WATCHED_USER (uid=$WATCHED_UID)..."
echo "Using syscalls for file permission monitoring: $PERM_SYSCALLS"

# Install auditd if not present
if ! command -v auditctl &>/dev/null; then
    apt-get update && apt-get install -y auditd
fi

# Build the -S flags for permission syscalls
PERM_S_FLAGS=""
IFS=',' read -ra SYSCALLS <<< "$PERM_SYSCALLS"
for sc in "${SYSCALLS[@]}"; do
    PERM_S_FLAGS="$PERM_S_FLAGS -S $sc"
done

# Write rules file
cat > /etc/audit/rules.d/clawav.rules << EOF
# ClawAV — Monitor openclaw user activity
# Generated by setup-auditd.sh
# Architecture: $ARCH

# Monitor all process execution by openclaw
-a always,exit -F arch=b64 -S execve -F uid=$WATCHED_UID -k clawav_exec

# Monitor file access to sensitive dirs
-w /etc/clawav/ -p rwxa -k clawav_tamper
-w /usr/local/bin/clawav -p rwxa -k clawav_tamper
-w /etc/systemd/system/clawav.service -p rwxa -k clawav_tamper

# Monitor privilege escalation attempts
-a always,exit -F arch=b64 -S setuid -S setgid -S setreuid -S setregid -F uid=$WATCHED_UID -k clawav_privesc

# Monitor network socket creation
-a always,exit -F arch=b64 -S socket -S connect -F uid=$WATCHED_UID -k clawav_net

# Monitor file permission changes (arch-specific syscalls)
-a always,exit -F arch=b64${PERM_S_FLAGS} -F uid=$WATCHED_UID -k clawav_perm

# Monitor module loading attempts
-a always,exit -F arch=b64 -S init_module -S finit_module -k clawav_module

# Monitor credential file reads (exfiltration / recon)
-w /home/openclaw/.openclaw/agents/main/agent/auth-profiles.json -p r -k clawav_cred_read
-w /home/openclaw/.aws/credentials -p r -k clawav_cred_read
-w /home/openclaw/.aws/config -p r -k clawav_cred_read
-w /home/openclaw/.ssh/id_ed25519 -p r -k clawav_cred_read
-w /home/openclaw/.ssh/id_rsa -p r -k clawav_cred_read
-w /home/openclaw/.env -p r -k clawav_cred_read
-w /home/openclaw/.openclaw/gateway.yaml -p r -k clawav_cred_read
EOF

# Reload rules
augenrules --load
echo "Auditd rules loaded. $(auditctl -l | grep -c clawav) ClawAV rules active."
